version: '3.8'

services:
  collector:
    build: .
    container_name: otelcol-custom
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "13133:13133"  # Health check
    volumes:
      - ./config.yaml:/root/config.yaml:ro
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
    networks:
      - otel-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:13133"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  otel-network:
    driver: bridge
